# Generated by Django 5.0.14 on 2026-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BespokeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Phone Number")),
                (
                    "garment_type",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Selected Garment"
                    ),
                ),
                (
                    "chest",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "shoulder",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "sleeve",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "neck",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "standard_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Standard Clothing Size"
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Body Height"
                    ),
                ),
                (
                    "fabrics",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated fabric names",
                        verbose_name="Selected Fabrics",
                    ),
                ),
                (
                    "color_notes",
                    models.TextField(blank=True, verbose_name="Color Preferences"),
                ),
                (
                    "inspiration_notes",
                    models.TextField(
                        blank=True, verbose_name="Inspiration & Design Thoughts"
                    ),
                ),
                (
                    "fit_notes",
                    models.TextField(blank=True, verbose_name="Fit Preferences"),
                ),
                (
                    "reference_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="references/",
                        verbose_name="Reference Drawing/Sketch",
                    ),
                ),
                (
                    "pinterest_link",
                    models.URLField(blank=True, verbose_name="Pinterest Board Link"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes visible only in admin",
                        verbose_name="Admin Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreed_no_returns",
                    models.BooleanField(
                        default=False, verbose_name="Agreed to No-Returns Policy"
                    ),
                ),
                (
                    "agreed_offline_payment",
                    models.BooleanField(
                        default=False, verbose_name="Agreed to Offline Payment"
                    ),
                ),
                (
                    "agreed_consultation",
                    models.BooleanField(
                        default=False, verbose_name="Agreed to Consultation Follow-up"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bespoke Request",
                "verbose_name_plural": "Bespoke Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Garment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Garment Title"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from title if left blank",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description for alt text and captions",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload high-resolution image (JPEG/PNG/WebP)",
                        upload_to="garments/",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("traditional", "Traditional Attire"),
                            ("shirts", "Shirts"),
                            ("caps", "Caps"),
                            ("sets", "Sets"),
                        ],
                        default="traditional",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in homepage social grid"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Unpublish to hide from gallery"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Garment",
                "verbose_name_plural": "Garments",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=200, verbose_name="Author Name"),
                ),
                (
                    "author_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Location (e.g. New York)",
                    ),
                ),
                ("text", models.TextField(verbose_name="Testimonial Text")),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
