# Generated by Django 5.0.14 on 2026-06-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_newslettersubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="BespokeSilhouette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Royal Indigo Agbada",
                        max_length=200,
                        verbose_name="Silhouette Name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short label shown under the card, e.g. Royal Agbada",
                        max_length=100,
                        verbose_name="Display Label",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload garment silhouette photo (JPEG/PNG/WebP)",
                        null=True,
                        upload_to="silhouettes/",
                        verbose_name="Silhouette Image",
                    ),
                ),
                (
                    "is_custom_vision",
                    models.BooleanField(
                        default=False,
                        help_text='If checked, renders as the open-ended "Custom Vision" card with an icon instead of a photo',
                        verbose_name="Custom Vision Card",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Unpublish to hide from the order form"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bespoke Silhouette",
                "verbose_name_plural": "Bespoke Silhouettes",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FabricSwatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Heavy Linen",
                        max_length=200,
                        verbose_name="Fabric Name",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#e0d6c8",
                        help_text="CSS hex colour used as the swatch preview background, e.g. #e0d6c8",
                        max_length=7,
                        verbose_name="Swatch Background Colour",
                    ),
                ),
                (
                    "texture_css",
                    models.TextField(
                        blank=True,
                        help_text="Optional inline CSS for a decorative overlay div on the swatch (background-image, opacity, etc.)",
                        verbose_name="Texture Overlay CSS",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo of the fabric; overrides the colour swatch if provided",
                        null=True,
                        upload_to="swatches/",
                        verbose_name="Swatch Image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Unpublish to hide from the order form"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fabric Swatch",
                "verbose_name_plural": "Fabric Swatches",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="hello@romcouture.com",
                        max_length=254,
                        verbose_name="Primary Contact Email",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="International format, e.g. +2348012345678",
                        max_length=30,
                        verbose_name="WhatsApp Number",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter / X URL"),
                ),
                (
                    "pinterest_url",
                    models.URLField(blank=True, verbose_name="Pinterest URL"),
                ),
                (
                    "hero_tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short headline shown on the homepage hero",
                        max_length=300,
                        verbose_name="Hero Tagline",
                    ),
                ),
                (
                    "hero_subtext",
                    models.TextField(
                        blank=True,
                        help_text="Supporting paragraph beneath the hero tagline",
                        verbose_name="Hero Subtext",
                    ),
                ),
                (
                    "footer_address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Studio Address"
                    ),
                ),
                (
                    "footer_copyright",
                    models.CharField(
                        blank=True,
                        help_text="Overrides default copyright. Leave blank to use default.",
                        max_length=200,
                        verbose_name="Footer Copyright Text",
                    ),
                ),
                (
                    "delivery_lead_time",
                    models.CharField(
                        default="4–6 weeks",
                        max_length=100,
                        verbose_name="Delivery Lead Time",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
