# Generated by Django 4.2.26 on 2026-06-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_bespokesilhouette_fabricswatch_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Subscription"),
        ),
    ]
