# Generated by Django 4.2.26 on 2026-06-19 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0004_newslettersubscription_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bespokerequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_bespokerequest_redacted",
                        "Can view redacted bespoke requests",
                    ),
                    (
                        "view_bespokerequest_full",
                        "Can view full bespoke requests including PII",
                    ),
                    (
                        "change_bespokerequest_progress",
                        "Can update bespoke request progress",
                    ),
                    (
                        "change_bespokerequest_internal_notes",
                        "Can edit admin/internal notes",
                    ),
                    (
                        "send_bespokerequest_completion_email",
                        "Can send bespoke request completion emails",
                    ),
                    ("cancel_bespokerequest", "Can cancel bespoke requests"),
                    (
                        "assign_bespokerequest",
                        "Can assign bespoke requests to designers",
                    ),
                ],
                "verbose_name": "Bespoke Request",
                "verbose_name_plural": "Bespoke Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="siteconfiguration",
            options={
                "permissions": [
                    ("manage_cms_users", "Can manage CMS users"),
                    ("manage_site_configuration", "Can manage site configuration"),
                    ("manage_cms_content", "Can manage CMS content"),
                    ("delete_cms_content", "Can delete CMS content"),
                    ("access_django_admin", "Can access Django admin"),
                ],
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.AddField(
            model_name="bespokerequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bespoke_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Designer",
            ),
        ),
        migrations.AddField(
            model_name="bespokerequest",
            name="work_notes",
            field=models.TextField(
                blank=True,
                help_text="Shared atelier progress notes visible to Admins, Supervisors, and Fashion Designers.",
                verbose_name="Work / Progress Notes",
            ),
        ),
        migrations.AlterField(
            model_name="bespokerequest",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Sensitive internal notes visible only to Admins and Supervisors.",
                verbose_name="Admin Notes",
            ),
        ),
        migrations.AlterField(
            model_name="bespokerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("ready_for_review", "Ready for Review"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BespokeRequestStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(max_length=30)),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cms_admin", "CMS Admin"),
                            ("django_admin", "Django Admin"),
                            ("api", "API"),
                            ("system", "System"),
                        ],
                        default="cms_admin",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bespoke_status_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="cms.bespokerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bespoke Request Status History",
                "verbose_name_plural": "Bespoke Request Status Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _create_cms_groups_and_permissions(apps),
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]


def _create_cms_groups_and_permissions(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    BespokeRequest = apps.get_model('cms', 'BespokeRequest')
    SiteConfiguration = apps.get_model('cms', 'SiteConfiguration')

    bespoke_content_type = ContentType.objects.get_for_model(BespokeRequest)
    site_content_type = ContentType.objects.get_for_model(SiteConfiguration)

    bespoke_permissions = {
        'view_bespokerequest_redacted': 'Can view redacted bespoke requests',
        'view_bespokerequest_full': 'Can view full bespoke requests including PII',
        'change_bespokerequest_progress': 'Can update bespoke request progress',
        'change_bespokerequest_internal_notes': 'Can edit admin/internal notes',
        'send_bespokerequest_completion_email': 'Can send bespoke request completion emails',
        'cancel_bespokerequest': 'Can cancel bespoke requests',
        'assign_bespokerequest': 'Can assign bespoke requests to designers',
    }
    site_permissions = {
        'manage_cms_users': 'Can manage CMS users',
        'manage_site_configuration': 'Can manage site configuration',
        'manage_cms_content': 'Can manage CMS content',
        'delete_cms_content': 'Can delete CMS content',
        'access_django_admin': 'Can access Django admin',
    }

    bespoke_perms = {
        codename: Permission.objects.get_or_create(
            codename=codename,
            content_type=bespoke_content_type,
            defaults={'name': name},
        )[0]
        for codename, name in bespoke_permissions.items()
    }
    site_perms = {
        codename: Permission.objects.get_or_create(
            codename=codename,
            content_type=site_content_type,
            defaults={'name': name},
        )[0]
        for codename, name in site_permissions.items()
    }

    admin_group = Group.objects.get_or_create(name='CMS Admins')[0]
    supervisor_group = Group.objects.get_or_create(name='CMS Supervisors')[0]
    designer_group = Group.objects.get_or_create(name='CMS Fashion Designers')[0]

    admin_group.permissions.set([*bespoke_perms.values(), *site_perms.values()])
    supervisor_group.permissions.set([
        bespoke_perms['view_bespokerequest_full'],
        bespoke_perms['change_bespokerequest_progress'],
        bespoke_perms['change_bespokerequest_internal_notes'],
        bespoke_perms['send_bespokerequest_completion_email'],
        bespoke_perms['cancel_bespokerequest'],
        bespoke_perms['assign_bespokerequest'],
        site_perms['manage_cms_content'],
    ])
    designer_group.permissions.set([
        bespoke_perms['view_bespokerequest_redacted'],
        bespoke_perms['change_bespokerequest_progress'],
    ])

    for user in User.objects.filter(is_superuser=True):
        user.groups.add(admin_group)
